# Generated by Django 3.2.11 on 2022-01-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeArea',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.place')),
            ],
            bases=('utils.place',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('administrativearea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrative_area.administrativearea')),
                ('postal', models.CharField(blank=True, max_length=16, null=True)),
                ('country_type', models.CharField(blank=True, max_length=128, null=True)),
                ('fips_10', models.CharField(blank=True, max_length=4, null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=16, null=True)),
                ('continent', models.CharField(blank=True, max_length=128, null=True)),
                ('subregion', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'country',
            },
            bases=('administrative_area.administrativearea',),
        ),
    ]
