# Generated by Django 3.2.11 on 2022-01-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='mpoly',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='mpoly',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='mpoly',
            new_name='geometry',
        ),
    ]
