# Generated by Django 3.2.11 on 2022-01-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
