# Generated by Django 3.2.11 on 2022-02-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0003_auto_20220128_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='adm1_code',
            new_name='geonames_id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='fips',
            new_name='whosonfirst_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='iso_3166_1_2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state_type',
        ),
        migrations.AddField(
            model_name='city',
            name='city_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_area.country'),
        ),
    ]
