# Generated by Django 3.2.11 on 2022-01-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0003_auto_20220114_1628'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrativearea',
            table='administrative_area',
        ),
    ]
