# Generated by Django 3.2.11 on 2022-02-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0004_auto_20220201_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'City type',
                'verbose_name_plural': 'City types',
                'db_table': 'city_type',
            },
        ),
        migrations.AlterModelOptions(
            name='statetype',
            options={'verbose_name': 'State type', 'verbose_name_plural': 'State types'},
        ),
        migrations.AlterField(
            model_name='city',
            name='city_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_area.citytype'),
        ),
    ]
