# Generated by Django 3.2.11 on 2022-01-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0004_alter_administrativearea_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('administrativearea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrative_area.administrativearea')),
                ('adm1_code', models.CharField(blank=True, max_length=16, null=True)),
                ('iso_3166_1_2', models.CharField(blank=True, max_length=16, null=True)),
                ('state_type', models.CharField(blank=True, max_length=16, null=True)),
                ('fips', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
            },
            bases=('administrative_area.administrativearea',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('administrativearea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrative_area.administrativearea')),
                ('adm1_code', models.CharField(blank=True, max_length=16, null=True)),
                ('iso_3166_1_2', models.CharField(blank=True, max_length=16, null=True)),
                ('state_type', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'state',
            },
            bases=('administrative_area.administrativearea',),
        ),
        migrations.RemoveField(
            model_name='country',
            name='wikidata_id',
        ),
    ]
