# Generated by Django 3.2.11 on 2022-01-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0005_auto_20220115_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativearea',
            options={'verbose_name': 'Administrative area', 'verbose_name_plural': 'Administrative areas'},
        ),
    ]
