# Generated by Django 3.2.11 on 2022-01-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0003_auto_20220115_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landform',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.place')),
            ],
            options={
                'db_table': 'landform',
            },
            bases=('utils.place',),
        ),
        migrations.CreateModel(
            name='BodyOfWater',
            fields=[
                ('landform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landform.landform')),
            ],
            options={
                'db_table': 'body_of_water',
            },
            bases=('landform.landform',),
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('landform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landform.landform')),
            ],
            options={
                'db_table': 'continent',
            },
            bases=('landform.landform',),
        ),
        migrations.CreateModel(
            name='OceanBodyOfWater',
            fields=[
                ('bodyofwater_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landform.bodyofwater')),
            ],
            options={
                'db_table': 'ocean_body_of_water',
            },
            bases=('landform.bodyofwater',),
        ),
    ]
