# Generated by Django 3.2.11 on 2022-01-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continent',
            old_name='mpoly',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='oceanbodyofwater',
            old_name='mpoly',
            new_name='geometry',
        ),
    ]
