# Generated by Django 3.2.11 on 2022-01-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyofwater',
            options={'verbose_name': 'Body of water', 'verbose_name_plural': 'Bodies of water'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'Continent', 'verbose_name_plural': 'Continents'},
        ),
        migrations.AlterModelOptions(
            name='landform',
            options={'verbose_name': 'Landform', 'verbose_name_plural': 'Landforms'},
        ),
        migrations.AlterModelOptions(
            name='oceanbodyofwater',
            options={'verbose_name': 'Ocean', 'verbose_name_plural': 'Oceans'},
        ),
    ]
