# Generated by Django 3.2.11 on 2022-02-03 10:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landform', '0002_auto_20220128_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyOfWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('name_long', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('wikipedia_url', models.URLField(blank=True, null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=16, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('natural_earth_id', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Body of water',
                'verbose_name_plural': 'Bodies of water',
                'db_table': 'body_of_water',
            },
        ),
        migrations.CreateModel(
            name='BodyOfWaterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Body of water type',
                'verbose_name_plural': 'Body of water types',
                'db_table': 'body_of_water_type',
            },
        ),
        migrations.DeleteModel(
            name='OceanBodyOfWater',
        ),
        migrations.AddField(
            model_name='bodyofwater',
            name='body_of_water_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landform.bodyofwatertype'),
        ),
    ]
