# Generated by Django 3.2.11 on 2022-02-03 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension



class Migration(migrations.Migration):

    dependencies = [
        ('landform', '0003_auto_20220203_1030'),
    ]

    operations = [
        CreateExtension('postgis_raster'),
        migrations.CreateModel(
            name='RasterTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
            options={
                'db_table': 'raster_test',
            },
        ),
    ]
