[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv/*
    | _build
    | buck-out
    | build
    | dist
  )/
    | migrations
    | dev.py
)
'''

[tool.isort]
skip_glob = "^(apps|dms|home|search)"
single_line_exclusions = ["os", "json"]