# Generated by Django 3.2.11 on 2022-01-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
        migrations.AlterModelTable(
            name='thing',
            table='thing',
        ),
    ]
