# Generated by Django 3.2.11 on 2022-01-15 21:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20220114_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='thing',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
