# Generated by Django 3.2.11 on 2022-01-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20220115_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='thing',
            options={'verbose_name': 'Thing', 'verbose_name_plural': 'Things'},
        ),
    ]
