# Generated by Django 3.2.11 on 2022-01-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0003_auto_20220115_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicStructure',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.place')),
            ],
            options={
                'db_table': 'civic_structure',
            },
            bases=('utils.place',),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('civicstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='civic_structure.civicstructure')),
                ('airport_type', models.CharField(blank=True, max_length=16, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=16, null=True)),
                ('gps_code', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'airport',
            },
            bases=('civic_structure.civicstructure',),
        ),
        migrations.CreateModel(
            name='BoatTerminal',
            fields=[
                ('civicstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='civic_structure.civicstructure')),
            ],
            options={
                'db_table': 'boat_terminal',
            },
            bases=('civic_structure.civicstructure',),
        ),
    ]
