# Generated by Django 3.2.11 on 2022-01-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterModelOptions(
            name='boatterminal',
            options={'verbose_name': 'Boat terminal', 'verbose_name_plural': 'Boat terminals'},
        ),
        migrations.AlterModelOptions(
            name='civicstructure',
            options={'verbose_name': 'Civic structure', 'verbose_name_plural': 'Civic structures'},
        ),
    ]
