# Generated by Django 3.2.11 on 2022-02-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civic_structure', '0003_scientificstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificStationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Scientific station type',
                'verbose_name_plural': 'Scientific station types',
                'db_table': 'science_station_type',
            },
        ),
        migrations.AddField(
            model_name='scientificstation',
            name='science_station_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civic_structure.scientificstationtype'),
        ),
    ]
