# Generated by Django 3.2.11 on 2022-02-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civic_structure', '0004_auto_20220201_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Airport type',
                'verbose_name_plural': 'Airport types',
                'db_table': 'airport_type',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='elevation_ft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='local_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='our_airports_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civic_structure.airporttype'),
        ),
    ]
