# Generated by Django 3.2.11 on 2022-02-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_area', '0005_auto_20220201_1155'),
        ('civic_structure', '0005_auto_20220203_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_area.country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_area.state'),
        ),
    ]
